import Aside from "@/components/Aside";
import Header from "@/components/header/Header";
import { getUiContent } from "@/lib/getUiContent";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Isms admin panel",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { navBar } = await getUiContent();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header navBar={navBar} />
        <Aside />

        <main className="p-4  sm:ml-64 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700">
          {children}
        </main>
      </body>
    </html>
  );
}
